### ISSUE TITLE
Jittery output

### ISSUE THREAD

**Issue by aindilis** [dtinth/html5-animation-video-renderer#9]
Hi,

First of all thanks for making this available!  This is a fantastic idea and execution, and is helping me out a lot.  I'm working on creating a system that uses reveal.js to render slides in an automatic video presentation generation system.  I've integrated your gsap-hello-world Javascript with the following script:

```
        <script src="dist/reveal.js"></script>
        <script src="plugin/zoom/zoom.js"></script>
        <script src="plugin/notes/notes.js"></script>
        <script src="plugin/search/search.js"></script>
        <script src="plugin/markdown/markdown.js"></script>
        <script src="plugin/highlight/highlight.js"></script>
        <script>

         // Also available as an ES module, see:                                                                                                               
         // https://revealjs.com/initialization/                                                                                                               
         Reveal.initialize({
             controls: true,
             progress: true,
             center: true,
             hash: true,
             autoSlide: 2500,
             // loop: true,                                                                                                                                    

             // Learn about plugins: https://revealjs.com/plugins/                                                                                             
             plugins: [ RevealZoom, RevealNotes, RevealSearch, RevealMarkdown, RevealHighlight ]
         });

        </script>
```

There is an issue though in that the video it's generating is jittery.  Here is an example:

https://frdcsa.org/~andrewdo/presentation.mp4

When I run the vue page through it, the time component seems randomize, i.e. it doesn't seem to progress linearly through time:

https://frdcsa.org/~andrewdo/vue.mp4

I was wondering if you had any ideas how I could fix this.  I've been substituting all kinds of CSS into the file to try to remove the jitter, but don't know what to do.

I installed on Debian 10, by installing Node.js 12, Yarn, and ffmpeg, but also had to install the following:

apt install libnss3-dev libgdk-pixbuf2.0-dev libgtk-3-dev libxss-dev

Thanks,
Andrew

**Comment by dtinth** [comment]
Hello @aindilis, thanks for your interest in this project.

One [constraint](https://github.com/dtinth/html5-animation-video-renderer#:~:text=the%20renderer%20needs%20to%20be%20able%20to%20display%20a%20freeze%20frame%20when%20requested) imposed by `html5-animation-video-renderer` is that when calling `seekToFrame()`, the webpage must **render a freeze frame**. This constraint allows the video to be rendered in a non real-time fashion. So consequently, the solution does not support CSS animations, and Reveal.js seems to depend on it.

> When I run the vue page through it, the time component seems randomize

The example pages require `?render` in the URL. i.e. `vue-starfield.html?render`. Without that, they run in real-time preview mode.

https://github.com/dtinth/html5-animation-video-renderer/blob/23bdaad8e54eded9984568b046a5e05b37ea4373/.circleci/config.yml#L24-L26

> I was wondering if you had any ideas how I could fix this

You’d have to make your Reveal.js animations renderable in freeze frame. I am not sure whether this is feasible or not.

But since you are using Linux, an alternative is to launch your presentation in a browser that renders onto Xvfb (e.g. using `xvfb-run` with `chrome --start-fullscreen`), then [use `ffmpeg` to record the screen in realtime](https://trac.ffmpeg.org/wiki/Capture/Desktop).

  ```bash
  ffmpeg \
    -video_size 1920x1080 \
    -draw_mouse 0 \
    -framerate 60 \
    -f x11grab -i :1.0 \
    -c:v libx264 \
    -crf 18 -preset ultrafast \
    recording.mkv -y
  ```

However this requires a server powerful enough to render the animation, record the screen, and encode a video at the desired frame rate in realtime. On Amazon EC2, a `c5.2xlarge` instance seems to work for this use case.

**Comment by aindilis** [comment]
Thank you so much for your awesome and quick reply!  After tinkering with the parameters to overcome some small issues I ran into, such as not having the MIT Magic Key and also the screen being shifted to the right by half the width, etc, this is the script I arrived at (please note it aggressively kills processes, so if someone wants to use it they should probably remove the killall commands, etc) - also one needs to replace file:///home/vagrant/index.html with the correct URI:

```
#!/usr/bin/env perl                                                                                                                                                                                                                                                                                                            

system 'killall Xvfb';
system 'xvfb-run --server-args="-screen 0 1920x1080x24" google-chrome --start-fullscreen --window-size=1920,1080 --window-position=0,0 file:///home/vagrant/index.html &';
sleep 1;
my $lines = `ps auxwww | grep Xvfb`;
my $xauth;
foreach my $line (split /\n/, $lines) {
  if ($line =~ /Xvfb :99 /) {
    if ($line =~ /-auth (.*?)$/) {
      $xauth = $1;
      last;
    }
  }
}

print "<$xauth>\n";
if ($xauth) {
  sleep 1;
  system "DISPLAY=:99 XAUTHORITY='$xauth' scrot";
  system"XAUTHORITY='$xauth' ffmpeg -video_size 1920x1080 -draw_mouse 0 -framerate 60 -f x11grab -i :99+0,0  -c:v libx264 -crf 18 -preset ultrafast recording.mkv -y &";
}
sleep 60;
system 'killall ffmpeg';
system 'killall Xvfb';

# ffmpeg -i recording.mkv -c:v libvpx -qmin 0 -crf 5 -b:v 1M -c:a libvorbis recording.webm 
```

Thanks so much for your help!  I think my presentation rendering will work now!  Fortunately I have a powerful enough desktop computer and the results were 99% good, but when I capture the final videos, I'll be sure to stop all other programs I can and also run with an appropriate "nice" setting.

Andrew
